In [ ]:
#tuple - like a list, it holds a collection of items. key difference is that tuples are immutable
#tuples are defined using parentheses
#lists are defined using square brackets
#tuples are immutable, meaning they cannot be changed after creation
#lists are mutable, meaning they can be changed after creation
#tuples are faster than lists
#tuples can be used as keys in dictionaries, while lists cannot
#tuples can be used to store multiple values in a single variable
#tuples can be used to return multiple values from a function

In [ ]:
#sets - unordered collection of unique items (will not retain order you add them in)
#sets are defined using curly braces
#sets are mutable, meaning they can be changed after creation
#sets are unordered, meaning they do not have a specific order

In [6]:
things = {'data', 'data', 'non-data'}
things

{'data', 'non-data'}

SET OPERATIONS

In [7]:
rainbow = {'red', 'orange', 'yellow', 'green', 'blue', 'indigo', 'violet'}
olympic_flag = {'red', 'yellow', 'green', 'blue', 'black'}

rainbow.difference(olympic_flag) #returns a set of items in rainbow that are not in olympic_flag



{'indigo', 'orange', 'violet'}

In [9]:
rainbow.symmetric_difference(olympic_flag) #returns a set of items that are in either rainbow or olympic_flag but not both

{'black', 'indigo', 'orange', 'violet'}

In [10]:
olympic_flag.difference(rainbow) #returns a set of items in olympic_flag that are not in rainbow


{'black'}

In [ ]:
olympic_flag.symmetric_difference(rainbow) #returns a set of items that are in either olympic_flag or rainbow but not both

{'black', 'indigo', 'orange', 'violet'}

In [12]:
rainbow.intersection(olympic_flag) #returns a set of items in both rainbow and olympic_flag

{'blue', 'green', 'red', 'yellow'}

In [13]:
rainbow.union(olympic_flag) #returns a set of items in either rainbow or olympic_flag


{'black', 'blue', 'green', 'indigo', 'orange', 'red', 'violet', 'yellow'}

DICTIONARIES    

In [14]:
# dictionaries - unordered collection of key-value pairs
# dictionaries are defined using curly braces
# dictionaries are mutable, meaning they can be changed after creation
# dictionaries are unordered, meaning they do not have a specific order
# dictionaries are indexed by keys, not by numbers
# dictionaries can be used to store multiple values in a single variable
# dictionaries can be used to return multiple values from a function

In [18]:
capitals = {'Canada': 'Ottawa', 
           'United States': 'Washington, D.C.',
           'Mexico': 'Mexico City'}

In [19]:
capitals

{'Canada': 'Ottawa',
 'United States': 'Washington, D.C.',
 'Mexico': 'Mexico City'}

In [21]:
olympic_cities = {'2020': 'Tokyo', 
                  '2016': 'Rio de Janeiro', 
                  '2012': 'London'}

In [22]:
olympic_cities

{'2020': 'Tokyo', '2016': 'Rio de Janeiro', '2012': 'London'}

In [24]:
all_olympic_hosts = {'summer' :olympic_cities,
                     'winter' : {2022: 'Beijing'} }

In [25]:
all_olympic_hosts

{'summer': {'2020': 'Tokyo', '2016': 'Rio de Janeiro', '2012': 'London'},
 'winter': {2022: 'Beijing'}}

FOR LOOPS

In [29]:
vowels = ['a', 'e', 'i', 'o', 'u']

In [30]:
for i in vowels:
    print (i)

a
e
i
o
u


In [34]:
for i in range(7):
    print (i, i*2)

0 0
1 2
2 4
3 6
4 8
5 10
6 12


In [40]:
input_files = ['data_01_csv', 'data_02_csv', 'data_03_csv', 'data_04_csv']
output_files = []

for i in input_files:
    output_file_name = 'processed_' + i.replace('.csv','xlsx')
    output_files.append(output_file_name)
    print (output_files)
                                            
        


['processed_data_01_csv']
['processed_data_01_csv', 'processed_data_02_csv']
['processed_data_01_csv', 'processed_data_02_csv', 'processed_data_03_csv']
['processed_data_01_csv', 'processed_data_02_csv', 'processed_data_03_csv', 'processed_data_04_csv']


In [ ]:
with open ('/Users/vbrej/python/05_src/data/slides_data/california_housing_test.csv') as f:
    print (f.readline())
#readlines() reads all lines in a file and returns a list of lines

"longitude","latitude","housing_median_age","total_rooms","total_bedrooms","population","households","median_income","median_house_value"



In [8]:
provinces = ['BC', 'Alberta', 'Saskatchewan', 'Manitoba', 'Ontario', 'Quebec', 'New Brunswick', 'Nova Scotia', 'Prince Edward Island', 'Newfoundland and Labrador']
with open('/Users/vbrej/python/04_this_cohort/live_code/provinces.txt','w') as province_file:
    province_file.writelines(provinces)

In [12]:
with open('/Users/vbrej/python/04_this_cohort/live_code/provinces.txt') as province_file:
    print(province_file.read())

BCAlbertaSaskatchewanManitobaOntarioQuebecNew BrunswickNova ScotiaPrince Edward IslandNewfoundland and Labrador


In [13]:
import os

In [18]:
os.getcwd()

'/Users/vbrej/python/02_activities/assignments'

In [19]:
os.chdir('/Users/vbrej/python/04_this_cohort/live_code')

In [20]:
os.getcwd()

'/Users/vbrej/python/04_this_cohort/live_code'

In [22]:
os. listdir()

['provinces.txt', '04_30_2025.ipynb', '04_29_2025.ipynb', '05_01_2025.ipynb']

In [26]:
cwd = os.getcwd()
full_paths = []

for i in os.listdir():
    temp = os.path.join(cwd, i)
    full_paths.append(temp)

In [27]:
full_paths

['/Users/vbrej/python/04_this_cohort/live_code/provinces.txt',
 '/Users/vbrej/python/04_this_cohort/live_code/04_30_2025.ipynb',
 '/Users/vbrej/python/04_this_cohort/live_code/04_29_2025.ipynb',
 '/Users/vbrej/python/04_this_cohort/live_code/05_01_2025.ipynb']

In [29]:
text = 'lavender is a small purple flower'

if os.path.exists ('plants.txt'):
    print ('plants.txt already exists')
else:   
    with open ('plants.txt', 'w') as f:
        f.write(text)

plants.txt already exists


In [30]:
os.getcwd() #get current working directory


'/Users/vbrej/python/04_this_cohort/live_code'

In [31]:
# CLASS = a blueprint for creating objects
# defines attributes and methods that the class will have
# OBJECT = an instance of a class
# attributes = variables that belong to the class
# methods = functions that belong to the class and can be called on objects of the class to perform actions/operations

OBJECT ORIENTED PROGRAMMING

In [33]:
car1_name = 'car1'
car1_make = 'Hunda'
car1_model = 'Civic'
car1_vin = "WHYRG"

car2_name = 'car2'
car2_make = 'Toyota'
car2_model = 'Corolla'
car2_vin = "BLOJDG"

#ineffecient, room for error, hard to maintain

class Car:
    def __init__(self, name, make, model, vin): #attributes
        self.name = name
        self.make = make
        self.model = model
        self.vin = vin

    def honk(self): #methods
        print('Honk! Honk!')

In [35]:
laura_car = Car('Car 1', 'Honda', 'Civic', 'WHYRG')

In [36]:
laura_car.make

'Honda'

In [37]:
import numpy as np

In [38]:
a = np.array([[1, 2, 3],
              [3, 2, 1]])

In [39]:
print(a.ndim)

2


In [40]:
print(a.shape)

(2, 3)


In [41]:
print(a.size)

6


In [42]:
print(a.dtype)

int64


In [43]:
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [44]:
np.ones_like(a) 

array([[1, 1, 1],
       [1, 1, 1]])

In [45]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [48]:
np.random.seed(1)
np.random.randint(1, 10, (3, 4))

array([[6, 9, 6, 1],
       [1, 2, 8, 7],
       [3, 5, 6, 3]])

In [50]:
multidim.array = np.tile(onedim.array, (5, 1))
multidim.array

NameError: name 'onedim' is not defined

In [52]:
b = np.array([[5, 4, 3, 2, 1, 0],
              [10, 8, 6, 4, 2, 0]])
b

array([[ 5,  4,  3,  2,  1,  0],
       [10,  8,  6,  4,  2,  0]])

In [53]:
b.T

array([[ 5, 10],
       [ 4,  8],
       [ 3,  6],
       [ 2,  4],
       [ 1,  2],
       [ 0,  0]])

In [54]:
b.reshape(4, 3)

array([[ 5,  4,  3],
       [ 2,  1,  0],
       [10,  8,  6],
       [ 4,  2,  0]])

In [55]:
b.flatten()

array([ 5,  4,  3,  2,  1,  0, 10,  8,  6,  4,  2,  0])

In [56]:
b

array([[ 5,  4,  3,  2,  1,  0],
       [10,  8,  6,  4,  2,  0]])

In [57]:
a

array([[1, 2, 3],
       [3, 2, 1]])

In [58]:
np.hstack((b, a))

array([[ 5,  4,  3,  2,  1,  0,  1,  2,  3],
       [10,  8,  6,  4,  2,  0,  3,  2,  1]])

In [62]:
np.vstack((b.reshape(4,3), a))

array([[ 5,  4,  3],
       [ 2,  1,  0],
       [10,  8,  6],
       [ 4,  2,  0],
       [ 1,  2,  3],
       [ 3,  2,  1]])

In [64]:
arr1 = np.array([[5, 10, 15, 20]])
arr1

array([[ 5, 10, 15, 20]])

In [66]:
arr2 = np.arange(5, 9)
arr2

array([5, 6, 7, 8])

In [67]:
arr1-arr2

array([[ 0,  4,  8, 12]])

In [68]:
arr1

array([[ 5, 10, 15, 20]])

In [69]:
arr1 * 2

array([[10, 20, 30, 40]])

In [70]:
np.median(arr1)

12.5